name: Python CI

description: Run Python tests

inputs:
  python-version:
    description: 'Python version to use'
    required: true
    default: '3.11'

runs:
  using: "composite"
  steps:
    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: ${{ inputs.python-version }}

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt

    - name: Install Python linters and formatters
      run: |
        pip install flake8 pylint black isort mypy bandit

    - name: Run tests
      run: pytest tests/

    - name: Run linters
      run: |
        flake8 .
        pylint .
        black --check .
        isort --check-only .
        mypy .
        bandit -r .
        radon cc . -nc
        radon mi .