name: Python CI

description: Run Python tests

inputs:
  python-version:
    description: 'Python version to use'
    required: true
    default: '3.11'

runs:
  using: "composite"
  steps:
    - name: Check out the repository
      uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: ${{ inputs.python-version }}

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
      shell: bash  # Указываем оболочку, например, bash

    - name: Install Python linters and formatters
      run: |
        pip install flake8 pylint black isort mypy bandit
      shell: bash  # Указываем оболочку

    - name: Run tests
      run: pytest tests/
      shell: bash  # Указываем оболочку

    - name: Run linters
      run: |
        flake8 .
        pylint .
        black --check .
        isort --check-only .
        mypy .
        bandit -r .
        radon cc . -nc
        radon mi .
      shell: bash  # Указываем оболочку