name: Python CI/CD

on:
  push:
    branches:
      - '**'
  pull_request:
    branches:
      - '**'

jobs:
  python-ci:
    runs-on: ubuntu-latest

    steps:
      # Запуск Python CI
      - name: Run Python CI
        uses: ./sources/test.yml
        with:
          python-version: '3.11'

  docker-publish:
    runs-on: ubuntu-latest
    needs: python-ci
    if: github.ref == 'refs/heads/main'

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set Repository Name
        id: repo
        run: echo "REPO_NAME=${GITHUB_REPOSITORY##*/}" >> $GITHUB_ENV

      - name: Publish Docker image
        uses: ./sources/docker.yml
        with:
          image-name: '${{ env.REPO_NAME }}'
